development:
  adapter: postgresql
  encoding: unicode
  database: ecomm_pricer_development
  pool: 5
  username: myapp
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: ecomm_pricer_test
  pool: 5
  username: myapp
  password: password1
